title: pjl
email: some.email@domain.com
description: >
  Maths and programming etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://pat-laub.github.io
twitter_username: PatrickLaub
github_username: Pat-Laub
google_analytics: UA-102813844-1
disqus:
  shortname: pat-laub-github-io

# Build settings`
markdown: kramdown
# highlighter: pygments
# theme: minima
# plugins_dir: [jekyll-feed, jekyll-scholar]
# plugins_dir:
#   - jekyll-feed
plugins:
  - jekyll-gist
  - jekyll-paginate-v2
sass:
    style: compressed
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
  blanklines: true

scholar:
  style: apa
# permalink: /:categories/:title/

gist:
  noscript: false

pagination:
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  per_page: 3
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  sort_field: 'date'
  sort_reverse: true

############################################################
