title: Patrick Laub
email: some.email@domain.com
description: >
  Maths and programming etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://pat-laub.github.io
twitter_username: PatrickLaub
github_username: Pat-Laub

# Build settings
markdown: kramdown

plugins:
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-gallery-generator
  - jekyll-tidy

sass:
    style: compressed

jekyll_tidy:
  compress_html: false

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  blanklines: true

scholar:
  style: apa
# permalink: /:categories/:title/

gist:
  noscript: false

pagination:
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  per_page: 3
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  sort_field: 'date'
  sort_reverse: true


gallery:
  dir: portfolios           # Path to the gallery
  title_prefix: ""          # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  thumbnail_size:
    x: 500                  # max width of thumbnails (in pixels)
    y: 375                  # max height of thumbnails (in pixels)
  scale_method: "fill"
  galleries:
    "2018":
      sort_reverse: true
    "2019":
      sort_field: "name"
    decade:
      sort_field: "name"