title: pjl
email: some.email@domain.com
description: >
  Maths and programming etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://pat-laub.github.io
twitter_username: PatrickLaub
github_username: Pat-Laub
google_analytics: UA-102813844-1
disqus:
  shortname: pat-laub-github-io

# Build settings`
markdown: kramdown
# highlighter: pygments
# theme: minima
# plugins_dir: [jekyll-feed, jekyll-scholar]
# plugins_dir:
#   - jekyll-feed
plugins:
  - jekyll-gist
sass:
    style: compressed
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
  blanklines: true

scholar:
  style: apa
# permalink: /:categories/:title/
