project:
  type: website
  output-dir: docs

website:
  title: "Patrick Laub"
  sidebar: false
  navbar: false
  google-analytics: "G-43924RE904"

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: false
    grid: 
      body-width: 1200px
      sidebar-width: 0px
      margin-width: 0px
    backgroundcolor: "#f4f4f4"
    fontcolor: "#646464"
    fontsize: 14pt

    resources:
      - ai
      - mine
      - ml
      - ras
      - thesis
      - favicon.ico
      - afric



